MVC_Husk.Web/Controllers/QueueController.cs
//
//  Copyright Info
//

using System.Web.Mvc;
using MVC_Husk.Infrastructure.BackgroundJobs;
using MVC_Husk.Infrastructure.Logging;
using MVC_Husk.Infrastructure.IdStore;
using MVC_Husk.Model;

namespace MVC_Husk.Controllers
{
    public class QueueController : ApplicationController
    {
        private IBackgroundJobManager _jobManager;
        private Jobs _jobs;

        public QueueController(ILogger logger, IBackgroundJobManager manager, IIdStore store)
            : base(store, logger)
        {
            _jobManager = manager;
            _jobs = new Jobs();
        }

        [Authorize]
        public ActionResult Index()
        {
            var jobs = _jobs.All();

            JobsViewModel model = new JobsViewModel
            {
                Jobs = jobs
            };

            ViewBag.Message = "All the jobs in the queue";

            return View(model);
        }

        [Authorize]
        public ActionResult LongRunning()
        {
            _jobManager.LongRunningJob(CurrentUser);

            ViewBag.Message = "A long running task has been added to the queue";

            return View();
        }
    }
}

MVC_Husk.Web/Controllers/UserController.cs
//
//  Copyright Info
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Husk.Infrastructure.IdStore;
using MVC_Husk.Infrastructure.Logging;
using MVC_Husk.Model;
using MVC_Husk.Infrastructure.Attributes;

namespace MVC_Husk.Controllers
{
    public class UserController : ApplicationController
    {
        Users _users;

        /// <summary>
        /// The overloaded constructor for the Account Controller
        /// </summary>
        /// <param name="idStore">The Forms Authentication Abstraction</param>
        /// <param name="logger">The Logging Abstraction</param>
        public UserController(IIdStore idStore, ILogger logger)
            : base(idStore, logger)
        {
            _users = new Users();
        }

        [Authorize]
        public ActionResult Index(int pageNum = 1, string searchTerms = "")
        {
            if (!IsAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            var users = _users.Paged(where: "Email like '%" + searchTerms + "%'", currentPage: pageNum, pageSize: 10);

            var viewModel = new UsersViewModel
            {
                People = users.Items,
                CurrentUser = this.CurrentUser,
                CurrentPage = pageNum,
                TotalRecords = users.TotalRecords,
                TotalPages = users.TotalPages
            };

            return View(viewModel);
        }

        [Authorize]
        public ActionResult Search(string search = "")
        {
            return RedirectToAction("Index", new { searchTerms = search });
        }

        [Authorize]
        public ActionResult Create()
        {
            if (!IsAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(string email)
        {
            if (!IsAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            var result = _users.Register(email, email, email, true);

            ViewBag.Message = result.Message;

            return View();
        }

        [Authorize]
        public ActionResult Suspend(string id)
        {
            if (!IsAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            _users.Update(new { IsActive = 0 }, id);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Activate(string id)
        {
            if (!IsAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            _users.Update(new { IsActive = 1 }, id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            if (!IsAdmin)
            {
                return RedirectToAction("Index", "Home");
            }

            _users.Delete(id);
            Logger.LogInfo("User " + CurrentUser.ID + " deleted user " + id);
            return RedirectToAction("Index");
        }
    }
}

MVC_Husk.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Public/Stylesheets/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Public/Stylesheets/ui-lightness/jquery-ui-1.8.13.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Public/Stylesheets/ui.jqgrid.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Public/Stylesheets/jquery.jqplot.min.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Public/javascripts/jquery-1.6.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Public/javascripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Public/javascripts/i18n/grid.locale-en.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Public/javascripts/jquery.jqGrid.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Public/javascripts/jquery.jqPlot.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Public/javascripts/jquery-ui-1.8.13.min.js")" type="text/javascript" ></script>
    <!--[if lt IE 9]><script src="@Url.Content("~/Public/javascripts/excanvas.min.js")" type="text/javascript" ></script><![endif]-->
    @RenderSection("pageJS", false)
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>MVC Husk</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            @Html.Partial("_NavigationPartial")
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

MVC_Husk.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

MVC_Husk.Web/Views/Shared/_NavigationPartial.cshtml
<nav>
    <ul id="menu">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Seasonal Products", "Index", "SeasonalProducts")</li>
        <li>@Html.ActionLink("User Maintenance", "Index", "User")</li>
        <li>@Html.ActionLink("Job Queue", "Index", "Queue")</li>
    </ul>
</nav>